In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("sales_data_sample.csv",encoding="latin1")

In [3]:
#Display the complete dataset.
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [6]:
#convert dataframe to ndarray
data=df.to_numpy()
data

array([[10107, 30, 95.7, ..., 'Yu', 'Kwai', 'Small'],
       [10121, 34, 81.35, ..., 'Henriot', 'Paul', 'Small'],
       [10134, 41, 94.74, ..., 'Da Cunha', 'Daniel', 'Medium'],
       ...,
       [10386, 43, 100.0, ..., 'Freyre', 'Diego', 'Medium'],
       [10397, 34, 62.24, ..., 'Roulet', 'Annette', 'Small'],
       [10414, 47, 65.52, ..., 'Yoshido', 'Juri', 'Medium']],
      shape=(2823, 25), dtype=object)

In [7]:
# Display the first 5 records.
# Display the last 5 records.
print("First 5 records:",data[:5])
print("Last 5 records:",data[5:])
df

First 5 records: [[10107 30 95.7 2 2871.0 '2/24/2003 0:00' 'Shipped' 1 2 2003
  'Motorcycles' 95 'S10_1678' 'Land of Toys Inc.' '2125557818'
  '897 Long Airport Avenue' nan 'NYC' 'NY' '10022' 'USA' nan 'Yu' 'Kwai'
  'Small']
 [10121 34 81.35 5 2765.9 '5/7/2003 0:00' 'Shipped' 2 5 2003
  'Motorcycles' 95 'S10_1678' 'Reims Collectables' '26.47.1555'
  "59 rue de l'Abbaye" nan 'Reims' nan '51100' 'France' 'EMEA' 'Henriot'
  'Paul' 'Small']
 [10134 41 94.74 2 3884.34 '7/1/2003 0:00' 'Shipped' 3 7 2003
  'Motorcycles' 95 'S10_1678' 'Lyon Souveniers' '+33 1 46 62 7555'
  '27 rue du Colonel Pierre Avia' nan 'Paris' nan '75508' 'France' 'EMEA'
  'Da Cunha' 'Daniel' 'Medium']
 [10145 45 83.26 6 3746.7 '8/25/2003 0:00' 'Shipped' 3 8 2003
  'Motorcycles' 95 'S10_1678' 'Toys4GrownUps.com' '6265557265'
  '78934 Hillside Dr.' nan 'Pasadena' 'CA' '90003' 'USA' nan 'Young'
  'Julie' 'Medium']
 [10159 49 100.0 14 5205.27 '10/10/2003 0:00' 'Shipped' 4 10 2003
  'Motorcycles' 95 'S10_1678' 'Corporate Gift Ideas Co.' '6505551386'
  '7734 Strong St.' nan 'San Francisco' 'CA' nan 'USA' nan 'Brown'
  'Julie' 'Medium']]
Last 5 records: [[10168 36 96.66 ... 'Hirano' 'Juri' 'Medium']
 [10180 29 86.13 ... 'Rance' 'Martine' 'Small']
 [10188 48 100.0 ... 'Oeztan' 'Veysel' 'Medium']
 ...
 [10386 43 100.0 ... 'Freyre' 'Diego' 'Medium']
 [10397 34 62.24 ... 'Roulet' 'Annette' 'Small']
 [10414 47 65.52 ... 'Yoshido' 'Juri' 'Medium']]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [8]:
# Display rows from index 10 to 20.
print("Rows from Index 10 to 20:",data[11:21])

Rows from Index 10 to 20: [[10237 23 100.0 7 2333.12 '4/5/2004 0:00' 'Shipped' 2 4 2004
  'Motorcycles' 95 'S10_1678' 'Vitachrome Inc.' '2125551500'
  '2678 Kingston Rd.' 'Suite 101' 'NYC' 'NY' '10022' 'USA' nan 'Frick'
  'Michael' 'Small']
 [10251 28 100.0 2 3188.64 '5/18/2004 0:00' 'Shipped' 2 5 2004
  'Motorcycles' 95 'S10_1678' 'Tekni Collectables Inc.' '2015559350'
  '7476 Moss Rd.' nan 'Newark' 'NJ' '94019' 'USA' nan 'Brown' 'William'
  'Medium']
 [10263 34 100.0 2 3676.76 '6/28/2004 0:00' 'Shipped' 2 6 2004
  'Motorcycles' 95 'S10_1678' 'Gift Depot Inc.' '2035552570'
  '25593 South Bay Ln.' nan 'Bridgewater' 'CT' '97562' 'USA' nan 'King'
  'Julie' 'Medium']
 [10275 45 92.83 1 4177.35 '7/23/2004 0:00' 'Shipped' 3 7 2004
  'Motorcycles' 95 'S10_1678' 'La Rochelle Gifts' '40.67.8555'
  '67, rue des Cinquante Otages' nan 'Nantes' nan '44000' 'France' 'EMEA'
  'Labrune' 'Janine' 'Medium']
 [10285 36 100.0 6 4099.68 '8/27/2004 0:00' 'Shipped' 3 8 2004
  'Motorcycles' 95 'S10_1678' "Marta's Replicas Co." '6175558555'
  '39323 Spinnaker Dr.' nan 'Cambridge' 'MA' '51247' 'USA' nan
  'Hernandez' 'Marta' 'Medium']
 [10299 23 100.0 9 2597.39 '9/30/2004 0:00' 'Shipped' 3 9 2004
  'Motorcycles' 95 'S10_1678' 'Toys of Finland, Co.' '90-224 8555'
  'Keskuskatu 45' nan 'Helsinki' nan '21240' 'Finland' 'EMEA' 'Karttunen'
  'Matti' 'Small']
 [10309 41 100.0 5 4394.38 '10/15/2004 0:00' 'Shipped' 4 10 2004
  'Motorcycles' 95 'S10_1678' 'Baane Mini Imports' '07-98 9555'
  'Erling Skakkes gate 78' nan 'Stavern' nan '4110' 'Norway' 'EMEA'
  'Bergulfsen' 'Jonas' 'Medium']
 [10318 46 94.74 1 4358.04 '11/2/2004 0:00' 'Shipped' 4 11 2004
  'Motorcycles' 95 'S10_1678' 'Diecast Classics Inc.' '2155551555'
  '7586 Pompton St.' nan 'Allentown' 'PA' '70267' 'USA' nan 'Yu' 'Kyung'
  'Medium']
 [10329 42 100.0 1 4396.14 '11/15/2004 0:00' 'Shipped' 4 11 2004
  'Motorcycles' 95 'S10_1678' 'Land of Toys Inc.' '2125557818'
  '897 Long Airport Avenue' nan 'NYC' 'NY' '10022' 'USA' nan 'Yu' 'Kwai'
  'Medium']
 [10341 41 100.0 9 7737.93 '11/24/2004 0:00' 'Shipped' 4 11 2004
  'Motorcycles' 95 'S10_1678' 'Salzburg Collectables' '6562-9555'
  'Geislweg 14' nan 'Salzburg' nan '5020' 'Austria' 'EMEA' 'Pipps'
  'Georg' 'Large']]

In [ ]:
#Display the SALES columnn
print("Sales Column:",data[:,4])

In [ ]:
# Display only the first 10 values from the SALES column.
sales=data[:,4]
print("First 10 records:",sales[:10])
#display last 10 values from Sales Column
print("Last 10 Records:",sales[10:])

In [ ]:
#Display only the QUANTITYORDERED values.
#display 10 records of quantity ordered 
quantity_ordered=data[:,1]
print("First 10 records of quantity_ordered:",quantity_ordered[:10])

In [ ]:
# Fetch the SALES, QUANTITYORDERED, and PRICEEACH values from the first record
sales=data[0,4]
print("First sale:",sales)
quantity_ordered=data[0,1]
print("First quantity ordered:",quantity_ordered)
price_each=data[0,2]
print("Price of first order:",price_each)

In [ ]:
#Find all records where SALES is greater than 1000.
sales=data[:,4].astype(float)
greater=data[sales>3000][:,4]
print("Records where sales is greater than 1000:",greater)

In [ ]:
# Find the total quantity ordered.
quantity_ordered=data[:,1].astype(int)
print("quamtity Ordered:",quantity_ordered)
print("Total Quantity Ordered:",np.sum(quantity_ordered))

In [ ]:
#Find all records from year 2003.
year=data[:,9].astype(int)
print("All records from year 2003:",data[year==2003])

In [15]:
# Find the average sales of records where quantity is greater than 30
quantity_ordered=data[:,2].astype(int)
sales=data[:,4].astype(float)
print("Average sales where quantity is greater than 30:",np.mean(sales[quantity_ordered>30]))

Average sales where quantity is greater than 30: 3569.1275908766925

In [9]:
# Display the record at index 0.
print("Record at index 0:",data[0])

Record at index 0: [10107 30 95.7 2 2871.0 '2/24/2003 0:00' 'Shipped' 1 2 2003 'Motorcycles'
 95 'S10_1678' 'Land of Toys Inc.' '2125557818' '897 Long Airport Avenue'
 nan 'NYC' 'NY' '10022' 'USA' nan 'Yu' 'Kwai' 'Small']

In [28]:
# Find the record having the highest sales
sales=data[:,4].astype(float)
print("Highest sales index row:",np.argmax(sales))
data[598]

Highest sales index row: 598

array([10407, 76, 100.0, 2, 14082.8, '4/22/2005 0:00', 'On Hold', 2, 4,
       2005, 'Vintage Cars', 170, 'S18_1749', 'The Sharp Gifts Warehouse',
       '4085553659', '3086 Ingle Ln.', nan, 'San Jose', 'CA', '94217',
       'USA', nan, 'Frick', 'Sue', 'Large'], dtype=object)

In [27]:
# Find the record having the lowest sales
sales=data[:,4].astype(float)
print("Lowest Sales Index row:",np.argmin(sales))
data[2249]

Lowest Sales Index row: 2249

array([10425, 11, 43.83, 6, 482.13, '5/31/2005 0:00', 'In Process', 2, 5,
       2005, 'Trucks and Buses', 54, 'S32_2509', 'La Rochelle Gifts',
       '40.67.8555', '67, rue des Cinquante Otages', nan, 'Nantes', nan,
       '44000', 'France', 'EMEA', 'Labrune', 'Janine', 'Small'],
      dtype=object)

In [36]:
# Find the ORDERNUMBER of records having sales greater than 10000.
order_number=data[:,3].astype(int)
sales=data[:,4].astype(float)
quantity=data[:,1].astype(int)
print("Order number of sales Greater than 10000:",order_number[sales>10000])
print("Quantity of sales greater than  10000:",quantity[sales>10000])

Order number of sales Greater than 10000: [ 8  6  3  6  9  2  2  2  6  9  2  1 13  3  2  2]
Quantity of sales greater than  10000: [45 47 48 50 66 46 44 76 50 60 46 65 55 76 43 46]

In [43]:
#calculate QUANTITYORDERED × PRICEEACH for every record.
quantity=data[:,1].astype(int)
price_each=data[:,2].astype(float)
result=quantity*price_each
print("calculation:",result[0:10])

calculation: [2871.   2765.9  3884.34 3746.7  4900.   3479.76 2497.77 4800.   2168.54
 4100.  ]

In [46]:
# Find the unique years present in the dataset
# Find the unique months present in the dataset
year=data[:,9].astype(int)
month=data[:,8].astype(int)
print("unique years:",np.unique(year))
print("month:",np.unique(month))

unique years: [2003 2004 2005]
month: [ 1  2  3  4  5  6  7  8  9 10 11 12]

In [53]:
#Create a result where sales above 3000 are marked as "High" and the rest as "Low".
sales=data[:,4].astype(int)
print("Sales greater than 3000:",np.where(sales>3000,"High","Low"))

Sales greater than 3000: ['Low' 'Low' 'High' ... 'High' 'Low' 'High']

In [65]:
#Find the average quantity of records where sales are greater than 3000
#Find the highest quantity among those records
quantity=data[:,1].astype(int)
sales=data[:,4].astype(int)
average=np.mean(quantity[sales>3000])
print("Average Quantity:",average)
print("Highest quantity:",np.max(quantity[sales>3000]))
index=np.where((sales>3000)&(quantity==np.max(quantity[sales>3000])))[0][0]
print("Record of highest quantity:",data[index])

Average Quantity: 38.892277741726154
Highest quantity: 97
Record of highest quantity: [10405 97 93.28 5 9048.16 '4/14/2005 0:00' 'Shipped' 2 4 2005
 'Classic Cars' 115 'S12_4675' 'Mini Caravy' '88.60.1555'
 '24, place Kluber' nan 'Strasbourg' nan '67000' 'France' 'EMEA' 'Citeaux'
 'Frederique' 'Large']

In [69]:
# Display the records at indexes 5, 15, 25, 35, and 45.
print("Record at indexes 5,15,25,35 and 45:",data[[5,15,25,35,45]])

Record at indexes 5,15,25,35 and 45: [[10168 36 96.66 1 3479.76 '10/28/2003 0:00' 'Shipped' 4 10 2003
  'Motorcycles' 95 'S10_1678' 'Technics Stores Inc.' '6505556809'
  '9408 Furth Circle' nan 'Burlingame' 'CA' '94217' 'USA' nan 'Hirano'
  'Juri' 'Medium']
 [10285 36 100.0 6 4099.68 '8/27/2004 0:00' 'Shipped' 3 8 2004
  'Motorcycles' 95 'S10_1678' "Marta's Replicas Co." '6175558555'
  '39323 Spinnaker Dr.' nan 'Cambridge' 'MA' '51247' 'USA' nan
  'Hernandez' 'Marta' 'Medium']
 [10417 66 100.0 2 7516.08 '5/13/2005 0:00' 'Disputed' 2 5 2005
  'Motorcycles' 95 'S10_1678' 'Euro Shopping Channel' '(91) 555 94 44'
  'C/ Moralzarzal, 86' nan 'Madrid' nan '28034' 'Spain' 'EMEA' 'Freyre'
  'Diego' 'Large']
 [10206 47 100.0 6 9064.89 '12/5/2003 0:00' 'Shipped' 4 12 2003
  'Classic Cars' 214 'S10_1949' 'Canadian Gift Exchange Network'
  '(604) 555-3392' '1900 Oak St.' nan 'Vancouver' 'BC' 'V3F 2K1' 'Canada'
  nan 'Tannamuri' 'Yoshi' 'Large']
 [10322 40 100.0 1 6000.4 '11/4/2004 0:00' 'Shipped' 4 11 2004
  'Classic Cars' 214 'S10_1949' 'Online Diecast Creations Co.'
  '6035558647' '2304 Long Airport Avenue' nan 'Nashua' 'NH' '62005' 'USA'
  nan 'Young' 'Valarie' 'Medium']]

In [72]:
# replace all sales values greater than 5000 with 5000 in a new array.
sales=data[:,4].astype(int)
new_sales=np.where(sales>5000,5000,sales)
print("New Sales:",new_sales)

New Sales: [2871 2765 3884 ... 5000 2116 3079]